### ISSUE TITLE
Fragen in Aussagen umwandeln

### ISSUE THREAD

**Issue by sandmann91** [BurosystemhausSchafer/buig#16]
Es gibt die Seite "Wer wir sind?"

Diese soll jetzt keine Fragen mehr stellen sondern Aussagen treffen. 
Nicht mehr "Wer sind wir?", sondern "Wer wir sind"
Nicht mehr "Was tun wir für Sie?" sondern "Was wir für Sie tun!"

usw...

![image](https://user-images.githubusercontent.com/14318498/156761199-854f20f8-f38d-436f-b1e3-d5b7d73be092.png)

**Comment by sandmann91** [comment]
Hi @DHamburg 
kleine Bemerkung noch dazu: 

- Die alte Seite hättest du löschen können (ist ja über das Repository noch nachvollziebar)
![image](https://user-images.githubusercontent.com/14318498/157625839-74fc0d72-a48c-4a20-a89a-a0f1123e8684.png)

- Dadurch, dass die Website schon Online ist, existiert der Link: "wer-wir-sind" schon und könnte ggf. in Google gefunden werden. Wenn du nun die Seite löscht, kann der Benutzer eine 404 Seite angezeigt bekommen. Deshalb habe ich auch hier über die `.htaccess` einen 301 Redirect eingerichten. [(Mehr Infos](https://www.trialta.de/blog/unterschied-zwischen-301-und-302-weiterleitung)
![image](https://user-images.githubusercontent.com/14318498/157626514-af932fd3-4157-455d-89c2-5bb248276570.png)

**Comment by sandmann91** [comment]
Du kannst den Issue wieder schließen, wenn du es gelesen hast.

**Comment by DHamburg** [comment]
> Hi @DHamburg 
> 
> kleine Bemerkung noch dazu: 
> 
> 
> 
> - Die alte Seite hättest du löschen können (ist ja über das Repository noch nachvollziebar)
> 
> ![image](https://user-images.githubusercontent.com/14318498/157625839-74fc0d72-a48c-4a20-a89a-a0f1123e8684.png)
> 
> 
> 
> - Dadurch, dass die Website schon Online ist, existiert der Link: "wer-wir-sind" schon und könnte ggf. in Google gefunden werden. Wenn du nun die Seite löscht, kann der Benutzer eine 404 Seite angezeigt bekommen. Deshalb habe ich auch hier über die `.htaccess` einen 301 Redirect eingerichten. [(Mehr Infos](https://www.trialta.de/blog/unterschied-zwischen-301-und-302-weiterleitung)
> 
> ![image](https://user-images.githubusercontent.com/14318498/157626514-af932fd3-4157-455d-89c2-5bb248276570.png)
> 
> 
> 
> 
> 
> 
> 
> 

Danke, das wusste ich noch nicht.
