### ISSUE TITLE
Button Farbe noch in Grün und nicht Lila

### ISSUE THREAD

**Issue by sandmann91** [BurosystemhausSchafer/buig#9]
![image](https://user-images.githubusercontent.com/14318498/155193027-a868f945-fdac-4a12-b02f-f93c58981dfc.png)

**Comment by DHamburg** [comment]
![Bildschirmfoto 2022-02-23 um 08 44 49](https://user-images.githubusercontent.com/90258825/155278992-0898943e-14c7-41b8-8c61-2a0cae5b3418.png)
